### ISSUE TITLE
Getting a "Failed to Login" notification even though I am certain my password and email is correct.

### ISSUE THREAD

**Issue by chrispan0** [chicohernando/MMM-Peloton#3]
![Screen Shot 2021-05-11 at 8 53 09 AM](https://user-images.githubusercontent.com/69996380/117818252-6c4e9700-b236-11eb-8e18-f9383695c46a.png)

My config is
{
  module: "MMM-Peloton",
  position: "bottom_left",
  header: "My Peloton Workouts",
  config: {
    debug: "true",
    username: "*****",
    password: "*****"
  }
},

And I get the error seen in the .png file. The debug isn't showing me anything at all.

**Comment by chicohernando** [comment]
Hi @Chris4285 -- I am also experiencing this issue and will be looking into a resolution for it soon.  I believe that Peloton has changed something with their API within the last couple of weeks.

I have updated the code on my device and am getting the following errors:
```
[2021-05-11 21:44:00.923] [LOG]    [MMM-Peloton:module_8_MMM-Peloton] error code: 1020
[2021-05-11 21:44:00.926] [LOG]    [MMM-Peloton:module_8_MMM-Peloton] Failed to authenticate
```

I will post here if/when I find a solution that is ready for you to try out.

**Comment by chicohernando** [comment]
@Chris4285 -- I believe that I have fixed the issue.  Can you do a `git pull` and try again and let me know if it works?

**Comment by chrispan0** [comment]
Just tried it again, works like a charm. Thanks!
